import type { Metadata } from "next";
import '../assets/css/global/index.css'
import Footer from "@/components/global/layout/footer";
import Header from "@/components/global/layout/header";

export const metadata: Metadata = {
  title: "Dolado",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="px-7 py-4 flex flex-col min-h-screen">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
